# Generated by Django 6.0.4 on 2026-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='quiz_submissions/'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
