# Generated by Django 6.0.4 on 2026-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_quizattempt_feedback_quizattempt_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice Only'), ('essay', 'Essay Only'), ('mixed', 'Mixed (Multiple Choice & Essay)')], default='multiple_choice', max_length=20),
        ),
    ]
