"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from importlib.util import find_spec
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [
        value.strip()
        for value in os.environ.get(name, default).split(',')
        if value.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-1hmx@2r*@3f5q6owxf2uf9(uoly(87h8#%p2&(bv9_^)(jqg3(',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1,localhost')

for host in env_list('RENDER_EXTERNAL_HOSTNAME'):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

for host in env_list('RAILWAY_PUBLIC_DOMAIN'):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

for host in env_list('VERCEL_URL'):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

if not DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        f'https://{host}'
        for host in ALLOWED_HOSTS
        if host not in ('*', '127.0.0.1', 'localhost') and not host.startswith('.')
    ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    
    # Local apps
    'accounts',
    'courses',
    'assessments',
    'interactions',
]

JAZZMIN_SETTINGS = {
    'site_title': 'E-Learn Admin',
    'site_header': 'E-Learn Administration',
    'site_brand': 'E-Learn',
    'welcome_sign': 'Welcome to E-Learn Admin',
    'copyright': 'E-Learning Platform',
    'search_model': ['accounts.CustomUser', 'courses.Course'],
    'topmenu_links': [
        {'name': 'Home', 'url': 'home', 'permissions': ['auth.view_user']},
        {'name': 'Courses', 'url': 'course_list', 'permissions': ['courses.view_course']},
        {'model': 'accounts.CustomUser'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'icons': {
        'accounts.CustomUser': 'fas fa-users',
        'accounts.UserProfile': 'fas fa-id-card',
        'courses.Category': 'fas fa-folder-open',
        'courses.Course': 'fas fa-book-open',
        'courses.Module': 'fas fa-layer-group',
        'courses.Lesson': 'fas fa-chalkboard-teacher',
        'courses.Enrollment': 'fas fa-user-graduate',
        'assessments.Quiz': 'fas fa-question-circle',
        'assessments.Question': 'fas fa-question',
        'assessments.Choice': 'fas fa-tasks',
        'assessments.QuizAttempt': 'fas fa-clipboard-check',
        'assessments.Assignment': 'fas fa-file-alt',
        'assessments.AssignmentSubmission': 'fas fa-file-upload',
        'interactions.UserProgress': 'fas fa-chart-line',
        'interactions.Discussion': 'fas fa-comments',
        'interactions.Comment': 'fas fa-comment-dots',
        'interactions.Certificate': 'fas fa-award',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if find_spec('whitenoise'):
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
DB_NAME = os.environ.get('DB_NAME')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=env_bool('DB_SSL_REQUIRE', True),
        )
    }
elif DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': DB_NAME,
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', ''),
            'PORT': os.environ.get('DB_PORT', ''),
        }
    }

    if env_bool('DB_SSL_REQUIRE', True):
        DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}
elif env_bool('REQUIRE_DATABASE_URL', False):
    raise ImproperlyConfigured(
        'Production database is not configured. Set DATABASE_URL, or set DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, and DB_PORT.'
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
staticfiles_storage = 'django.contrib.staticfiles.storage.StaticFilesStorage'
if not DEBUG and find_spec('whitenoise'):
    staticfiles_storage = 'whitenoise.storage.CompressedStaticFilesStorage'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': staticfiles_storage,
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.CustomUser'

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
